[package]
name = "pg_split_dump"
version = "0.2.0"
edition = "2021"
authors = ["Marko Tiikkaja <marko@joh.to>"]

[dependencies]
getopts = "0.2"
postgres = "0.19"
byteorder = "1"
tar = "0.4"

[features]
warnings-as-errors = []
