name: CI
on:
  push:
     branches:
       - main
       - ghat
jobs:
  test:
    name: Build debug binary Ubuntu Bionic
    runs-on: ubuntu-latest
    container:
        image: ubuntu:bionic
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install curl and certificates
        run: apt-get update && apt-get install -y curl ca-certificates

      - name: Install packages for building binaries
        run: apt-get install -y build-essential

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build pg_split_dump
        run: cargo build --verbose

      - name: Archive built pg_split_dump binary
        uses: actions/upload-artifact@v3
        with:
          name: pg_split_dump
          path: target/debug/pg_split_dump

      - name: Build tar_diff
        working-directory: tar_diff
        run: cargo build --verbose

      - name: Archive built tar_diff binary
        uses: actions/upload-artifact@v3
        with:
          name: tar_diff
          path: tar_diff/target/debug/tar_diff
