name: Test
on:
  push:
     branches:
       - ghat
       - main

  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        pg: [17, 16, 15, 14, 13]
    name: PostgreSQL ${{ matrix.pg }}
    runs-on: ubuntu-latest
    container: pgxn/pgxn-tools
    steps:
      - name: Start PostgreSQL ${{ matrix.pg }}
        run: pg-start ${{ matrix.pg }}
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build pg_split_dump
        run: cargo build --verbose --features=warnings-as-errors
      - name: Build tar_diff
        working-directory: tar_diff
        run: cargo build --verbose --features=warnings-as-errors
      - name: Build create_expected_archive
        working-directory: tests/bin/create_expected_archive
        run: cargo build --verbose --features=warnings-as-errors
      - name: Test on PostgreSQL ${{ matrix.pg }}
        working-directory: tests
        run: ./run_tests.sh
